packages_to_install:
  #
  # Necessities
  #
  - gedit
  - git
  - gnome-terminal
  - python3-devel
  - python3-pip
  - firefox

  #
  # Quality of Life
  #
  - bash-completion
  - dos2unix
  - gitk
  - gnome-tweaks
  - htop
  - libcanberra-gtk2

  #
  # Containers
  #
  - podman
  - podman-docker
