name: Docker Image CI

on:
  push:
    branches: [ "main", "dev", 'releases/**', 'issue_**' ]
  pull_request:
    branches: [ "main", "dev"  ]
    
env:
  REGISTRY: ghcr.io
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract Metadata (tags and labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build & Push Docker Image(s)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # removing linux/arm64 due to https://github.com/haisamido/nos3-64/actions/runs/15981698304/job/45077321714#step:6:9123 TBD
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
