name: Docker Image CI

on:
  push:
    branches: [ "main", "dev", 'releases/**', 'issue_**' ]
  pull_request:
    branches: [ "main", "dev"  ]
    
env:
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Extract Metadata (tags and labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build & Push Docker Image(s)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
#          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}, ${{ env.REGISTRY }}/nos3-64:dev
          labels: ${{ steps.meta.outputs.labels }}
